heat_template_version: 2016-04-08

description: >
  HOT template to create a new neutron network plus a router to the public
  network, and for deploying two servers into the new network. 

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
    default: aio-key
  image:
    type: string
    description: Name of image to use for servers
    default: FC23-Nginx-Docker-CL   
  flavor:
    type: string
    description: Flavor to use for servers
    default: Demo
  public_net_id:
    type: string
    description: ID or name of public network for which floating IP addresses will be allocated
    default: Public-Network
  private_net_name:
    type: string
    description: Name of private network to be created
    default: test_net
  private_net_v6:
    type: string
    description: Private IPv6 subnet address
    default: 2001:db8:cafe:1e::/64
  private_net_v6_gateway:
    type: string
    description: Private network gateway address
    default: 2001:db8:cafe:1e::1
  private_net_v6_pool_start:
    type: string
    description: Start of private network IP address allocation pool
    default: 2001:db8:cafe:1e::2
  private_net_v6_pool_end:
    type: string
    description: End of private network IP address allocation pool
    default: 2001:db8:cafe:1e:ffff:ffff:ffff:fffe
  dns_nameservers:
    type: string
    description: Add DNS nameserver(s)
    default: 2001:db8:cafe:a::e

resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }

  private_v6_subnet:
    type: OS::Neutron::Subnet
    properties:
      ip_version: 6
      ipv6_address_mode: slaac
      ipv6_ra_mode: slaac
      network: { get_resource: private_net }
      cidr: { get_param: private_net_v6 }
      gateway_ip: { get_param: private_net_v6_gateway }
      allocation_pools:
        - start: { get_param: private_net_v6_pool_start }
          end: { get_param: private_net_v6_pool_end }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net_id }

  router_interface_v6:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: private_v6_subnet }

  server1:
    type: OS::Nova::Server
    properties:
      name: Server1
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: private_net }
      config_drive: "true"
      user_data_format: RAW
      user_data: |
        #cloud-config
        fqdn: v6onlyinstance1.example.com  
      security_groups: [{ get_resource: server_security_group }]

  server2:
    type: OS::Nova::Server
    properties:
      name: Server2
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: private_net }
      config_drive: "true"
      user_data_format: RAW
      user_data: |
        #cloud-config
        fqdn: v6onlyinstance2.example.com
      security_groups: [{ get_resource: server_security_group }]
  
  server_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Heat-deployed security group.
      name: heat-security-group
      rules: [
        {remote_ip_prefix: "::/0",
        ethertype: IPv6,
        protocol: tcp,
        port_range_min: 22,
        port_range_max: 22},
        {remote_ip_prefix: "::/0",
        ethertype: IPv6,
        protocol: icmp},
        {remote_ip_prefix: "::/0",
        ethertype: IPv6,
        protocol: tcp,
        port_range_min: 80,
        port_range_max: 80}]

  monitor:
    type: OS::Neutron::HealthMonitor
    properties:
      type: TCP
      delay: 5
      max_retries: 5
      timeout: 5
  pool:
    type: OS::Neutron::Pool
    properties:
      protocol: HTTP
      monitors: [{get_resource: monitor}]
      subnet: { get_resource: private_v6_subnet }
      lb_method: ROUND_ROBIN
      vip:
        protocol_port: 80
  lb:
    type: OS::Neutron::LoadBalancer
    properties:
      protocol_port: 80
      pool_id: {get_resource: pool}

  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_resource: pool}
      address: {get_attr: [server1, first_address]}
      protocol_port: 80
  member1:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_resource: pool}
      address: {get_attr: [server2, first_address]}
      protocol_port: 80

